# Generated by Django 5.1.3 on 2024-12-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
