# Generated by Django 5.1.3 on 2024-12-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type_id',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
