# Generated by Django 5.1.3 on 2024-12-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='transaction_type_id',
        ),
        migrations.RenameField(
            model_name='transactiontype',
            old_name='transaction_id',
            new_name='id',
        ),
    ]
